# Enable mouse usage
set -g mouse on

# Ensure new splits and windows open in current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
