# Everforest {{ .mode }} soft palette for kitty
background {{ .kitty.background }}
foreground {{ .kitty.foreground }}

color0 {{ .ansi.color0 }}
color1 {{ .ansi.color1 }}
color2 {{ .ansi.color2 }}
color3 {{ .ansi.color3 }}
color4 {{ .ansi.color4 }}
color5 {{ .ansi.color5 }}
color6 {{ .ansi.color6 }}
color7 {{ .ansi.color7 }}

color8 {{ .ansi.color8 }}
color9 {{ .ansi.color9 }}
color10 {{ .ansi.color10 }}
color11 {{ .ansi.color11 }}
color12 {{ .ansi.color12 }}
color13 {{ .ansi.color13 }}
color14 {{ .ansi.color14 }}
color15 {{ .ansi.color15 }}

active_tab_foreground   {{ .kitty.active_tab_foreground }}
active_tab_background   {{ .kitty.active_tab_background }}
inactive_tab_foreground {{ .kitty.inactive_tab_foreground }}
inactive_tab_background {{ .kitty.inactive_tab_background }}
tab_bar_background      {{ .kitty.tab_bar_background }}
